baseurl = "http://www.alijnabavi.info/blog/"
languageCode = "en-us"
title = "My New Hugo Site"
[params]
	sidebartitle = "My Site"
	sidebartagline = "Is super awesome"
[taxonomies]
  tag = "tags"
  category = "categories"
