baseurl = "http://www.alijnabavi.info/blog/"
languageCode = "en-us"
title = "[AliJNabavi.info] My New Hugo Site"
[params]
	sidebartitle = "My Site"
	sidebartagline = "Is super awesome"
	description = "Ali Nabavi's blog"
	twitter = "@alijnabavi"
	github = "hourback"
	gplus = "AliNabavi"
	linkedin = "AliJNabavi"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[author]
	name = "Ali Nabavi"
	github = "hourback"
	linkedin = "AliJNabavi"
	twitter = "@alijnabavi"

